#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server.


# Check if the number of parameters is correct
if [[ $# -ne 4 ]]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Extract the parameters
file_path=$1
server_ip=$2
username=$3
ssh_key=$4

# Using scp to transfer the file and also to check the exit code of scp
if ! scp -o "StrictHostKeyChecking no" -i "$ssh_key" "$file_path" "$username@$server_ip:~/"; then
	echo "Error: Failed to transfer the file."
	exit 1
fi
