#!/usr/bin/env bash
# A Bash script that configures a new Ubuntu machine to meet some requirements as a server.

# Update the package list and install nginx
apt update
apt install -y nginx

# Replace the default Nginx configuration with a custom configuration
cat << 'EOF' > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Restart Nginx to apply the changes
service nginx restart