#!/usr/bin/env bash
# Configure lb-01 with HAproxy so that it send traffic to web-01 and web-02
# distributing requests using a roundrobin algorithm

# Update package information
sudo apt-get -y update

# Install and start HAProxy
sudo apt-get -y install haproxy
sudo service haproxy start

# edit config file
server_config=\
"
frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 491649-web-01:80 check
    server web-02 491649-web-02:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAProxy to apply changes
sudo service haproxy restart
