#!/usr/bin/env bash
# SQL backing up
# Get the current date in the required format
DATE=$(date +"%d-%m-%Y")
mysqldump -u root --password="$1" --all-databases > backup.sql
tar -czvf "${DATE}.tar.gz" backup.sql
