#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd.
# The script only displays:
# - username
# - user id
# - Home directory path for the user

while IFS=':' read -r USERNAME PASSWORD U_ID GID UID_INFO HOME_DIR CMD_SH; do
	echo "The user $USERNAME is part of the $GID gang, lives in $HOME_DIR and rides $CMD_SH. $U_ID's place is protected by the passcode $PASSWORD, more info about the user here: $UID_INFO"
done < /etc/passwd
