#!/usr/bin/env bash
# A Bash script that groups visitors by IP and HTTP status code, after it  displays the visitor IP along with the HTTP status code from the Apache log file.
# The exact format must be:
# OCCURENCE_NUMBER   IP   HTTP_CODE
# In list format
# Ordered from the greatest to the lowest number of occurrences

awk '{print $1 " "  $9}' FS=' ' apache-access.log | sort | uniq -c | sort -nr
