#!/usr/bin/env bash
# A Bash script that gives information about the school file.

file="school"
if [ -e "$file" ]; then
	echo "$file file exists"
	[[ ! -s "$file" ]] && echo "$file file is empty"
	[[ -s "$file" ]] && echo "$file file is not empty"
	[[ -f "$file" ]] && echo "$file file is a regular file"

else
	echo "$file file does not exist"
fi
