#!/usr/bin/env bash
# A Bash script that gives information about the school file.

file="school"
if [ -e "$file" ]; then
	echo -e "$file file exists"
	if [ ! -s "$file" ]; then
		echo -e "$file file is empty"
	else
		echo -e "$file file is not empty"
	fi

	if [ -f "$file" ]; then
		echo -e "$file file is a regular file"
	fi

else
	echo -e "$file file does not exist"
fi
