#!/bin/bash
sudo apt update
sudo apt install -y ufw
sudo sed -i 's/IPV6=no/IPV6=yes/g' /etc/default/ufw
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw default deny incoming
sudo ufw enable
